# -*- coding: utf-8 -*-
"""Copy of rasachatpgt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dyeCJUYEhluA-ghfYNCrsqGW5u7gKTo
"""

!pip install chatterbot

!pip install pyyaml>=5.3.1
!pip install srsly==2.4.0

!pip install spacy==3.4.0

!pip install chatterbot==1.0.5
!pip install spacy==2.1

!pip install spacy

!pip install --ignore-installed PyYAML

!pip install chatterbot-corpus

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot("GoogleSearch")

from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import ListTrainer

import requests
import re

class GoogleSearchTrainer(object):
   def get_response(self, statement):
      query = statement.text
      query = re.sub('[^0-9a-zA-Z]+', '+', query)
      google_url = "https://www.google.com/search?q=" + query
      response = requests.get(google_url)
      return response.text

trainer = GoogleSearchTrainer()
bot.set_trainer(Trainer)

bot.set_trainer(Trainer)

chatbot.train()

response = chatbot.get_response("Integrate Google Search with ChatterBot")
print(response)